site_name: My Documentations, Our Documentations
copyright: |
  Documentation under Creative Commons version 4, otherwise noted.<br/>Indonesia version.<br/>
  <i>Kurukurukuru - Kururing -- Herta (Honkai: Star Rail)</i>

extra_css:
  - "-nahida/-additional.css"

extra:
  homepage: http://start.1423.my.id
  social:
    - icon: fontawesome/brands/youtube
      name: Min777A - YouTube
      link: https://youtube.com/@Min777A
    - icon: fontawesome/brands/github
      name: Repositori
      link: http://github.com/Abyanu163/docs/tree/Nahida/docs
    - icon: fontawesome/brands/github
      name: Abyanu163 @ GitHub
      link: http://github.com/Abyanu163

theme: 
  name: material
  icon:
    logo: material/file-document-outline
  language: id
  font: false # Recommended in Chinese block Google
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: teal
      accent: blue
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: cyan
      accent: light blue

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg