site_name: My Documentations, Our Documentations
author: Abyanu163
copyright: |
  Documentation under Creative Commons version 4, otherwise noted. Indonesia version.
repo_url: Abyanu163/docs
edit_uri: edit/Nahida/docs
view_uri: blob/Nahida/docs
extra_css:
  - "-nahida/-additional.css"

theme: 
  name: material
  language: id
  icon:
    repo: fontawesome/solid/trash
    edit: material/file-document-edit-outline
    view: material/file-document-multiple-outline
  font: false # Recomended in Chinese block Google
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
  palette:
    primary: black
    accent: teal