site_name: My Documentations, Our Documentations
copyright: |
  Documentation under Creative Commons version 4, otherwise noted. Indonesia version.

repo_url: https://github.com/Abyanu163/docs
edit_uri: edit/Nahida/docs
view_uri: blob/Nahida/docs

extra_css:
  - "-nahida/-additional.css"

theme: 
  name: material
  language: id
  icon:
    repo: fontawesome/solid/trash
    edit: material/file-document-edit-outline
    view: material/file-document-multiple-outline
  font: false # Recomended in Chinese block Google
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.view
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
        primary: black
        accent: blue
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        primary: black
        accent: teal

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg