site_name: My Documentations, Our Documentations
author: Abyanu163
copyright: |
  Documentation under Creative Commons version 4, otherwise noted. Indonesia version.

theme: 
  name: material
  language: id
  font: false # Recomended in Chinese block Google
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  pallete:
    - scheme: default
      toggle: 
        icon: material/lightbulb
        name: "Swicth to monitor background"
      primary: black
      accent: cyan
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to paper background"
      primary: white