site_name: My Documentations, Our Documentations
author: Abyanu163
copyright: |
  Documentation under Creative Commons version 4, otherwise noted. Indonesia version.
repo_url: https://github.com/Abyanu163/docs
edit_uri: edit/Nahida/docs
extra_css:
  - "-nahida/-addtional.css"
  - stylesheets/extra.css

theme: 
  name: material
  language: id
  icon:
    repo: fontawesome/solid/trash
    edit: material/file-document-edit-outline
    view: material/file-document-multiple-outline
  font: false # Recomended in Chinese block Google
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
  palette:
    - scheme: default
      toggle: 
        icon: material/lightbulb
        name: "Swicth to monitor background"
      primary: black
      accent: cyan
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to paper background"
      primary: white