site_name: "DOCS-ID#1423"
copyright: |
  Documentation under Creative Commons version 4, otherwise noted.<br/>
  <i>Kurukurukuru - Kururing -- Herta (Honkai: Star Rail)</i>

nav:
  - "Start/Mulai": "/index.md"
  - "Begin/Awal": "/INTRO/"
  - "End/Terakhir": "/END/"

extra_css:
  - "-nahida/-additional.css"

extra:
  homepage: //root.1423.my.id
  alternate:
  - name: Indonesia
    link: /
    lang: id
  - name: English
    link: /en/
    lang: en
  social:
    - icon: fontawesome/brands/github
      name: Repositori
      link: http://github.com/Abyanu163/docs/tree/Nahida/docs
    - icon: fontawesome/brands/github
      name: Abyanu163 @ GitHub
      link: http://github.com/Abyanu163

theme:
  name: material
  icon:
    logo: material/file-document-outline
  language: id
  font: false # Recommended in Chinese block Google
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - navigation.sections
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: blue
      accent: blue
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: light blue
      accent: teal

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - toc
  - tables

plugins:
  - search
  - i18n:
      default_language: id
      languages:
        id:
          name: Indonesia
          build: false
        en:
          name: English
          build: true
