# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: "Nahida_SetMKDOCS: Deploy with MkDocs"

on:
  push:
    branches: [ "Nahida" ]
  pull_request:
    branches: [ "Nahida" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Starting...
      run: echo "Get ready for test deploy & deploy"
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Caching ENV setup
      run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
    - uses: actions/cache@v3
      with:
        key: mkdocs-material-${{ env.cache_id }}
        path: .cache
        restore-keys: |
          mkdocs-material-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs-material
    - name: Force MkDocs
      run: mkdocs gh-deploy --force
    - name: Exit code
      run: echo "END"
